local addonName, addonData = ...
addonData.lootDb = {
	[16934]={["name"]="Warlock T2 Bracers",["dkp"]="5",["note"]="",["role"]="Warlock"},
	[16933]={["name"]="Warlock T2 Belt",["dkp"]="60",["note"]="",["role"]="Warlock"},
	[16927]={["name"]="Warlock T2 Boots",["dkp"]="60",["note"]="",["role"]="Warlock"},
	[16928]={["name"]="Warlock T2 Gloves",["dkp"]="5",["note"]="",["role"]="Warlock"},
	[16932]={["name"]="Warlock T2 Shoulders",["dkp"]="30",["note"]="",["role"]="Warlock"},
	[16931]={["name"]="Warlock T2 Chest",["dkp"]="5",["note"]="",["role"]="Warlock"},
	[16918]={["name"]="Mage T2 Bracers",["dkp"]="30",["note"]="",["role"]="Mage"},
	[16818]={["name"]="Mage T2 Belt",["dkp"]="30",["note"]="",["role"]="Mage"},
	[16912]={["name"]="Mage T2 Boots",["dkp"]="5",["note"]="",["role"]="Mage"},
	[16913]={["name"]="Mage T2 Gloves",["dkp"]="60",["note"]="",["role"]="Mage"},
	[16917]={["name"]="Mage T2 Shoulders",["dkp"]="5",["note"]="",["role"]="Mage"},
	[16916]={["name"]="Mage T2 Chest",["dkp"]="5",["note"]="",["role"]="Mage"},
	[16926]={["name"]="Priest T2 Bracers",["dkp"]="60",["note"]="",["role"]="Heal-Priest"},
	[16925]={["name"]="Priest T2 Belt",["dkp"]="60",["note"]="",["role"]="Heal-Priest"},
	[16919]={["name"]="Priest T2 Boots",["dkp"]="60",["note"]="",["role"]="Heal-Priest"},
	[16920]={["name"]="Priest T2 Gloves",["dkp"]="60",["note"]="",["role"]="Heal-Priest"},
	[16924]={["name"]="Priest T2 Shoulders",["dkp"]="70",["note"]="",["role"]="Heal-Priest"},
	[16923]={["name"]="Priest T2 Chest",["dkp"]="70",["note"]="",["role"]="Heal-Priest"},
	[16964]={["name"]="Warrior T2 Bracers",["dkp"]="60",["note"]="",["role"]="Tank-Warrior > Warrior"},
	[16965]={["name"]="Warrior T2 Belt",["dkp"]="60",["note"]="",["role"]="Tank-Warrior > Warrior"},
	[16961]={["name"]="Warrior T2 Boots",["dkp"]="60",["note"]="",["role"]="Tank-Warrior > Warrior"},
	[16960]={["name"]="Warrior T2 Gloves",["dkp"]="60",["note"]="",["role"]="Tank-Warrior > Warrior"},
	[16966]={["name"]="Warrior T2 Shoulders",["dkp"]="70",["note"]="",["role"]="Tank-Warrior > Warrior"},
	[16959]={["name"]="Warrior T2 Chest",["dkp"]="70",["note"]="",["role"]="Tank-Warrior > Warrior"},
	[16911]={["name"]="Rogue T2 Bracers",["dkp"]="60",["note"]="",["role"]="Rogue"},
	[16910]={["name"]="Rogue T2 Belt",["dkp"]="60",["note"]="",["role"]="Rogue"},
	[16906]={["name"]="Rogue T2 Boots",["dkp"]="60",["note"]="",["role"]="Sword-Rogue > Rogue"},
	[16907]={["name"]="Rogue T2 Gloves",["dkp"]="60",["note"]="",["role"]="Sword-Rogue > Rogue"},
	[16832]={["name"]="Rogue T2 Shoulders",["dkp"]="70",["note"]="",["role"]="Sword-Rogue > Rogue"},
	[16905]={["name"]="Rogue T2 Chest",["dkp"]="70",["note"]="",["role"]="Rogue"},
	[16935]={["name"]="Hunter T2 Bracers",["dkp"]="60",["note"]="",["role"]="Hunter"},
	[16941]={["name"]="Hunter T2 Belt",["dkp"]="60",["note"]="",["role"]="Hunter"},
	[16936]={["name"]="Hunter T2 Boots",["dkp"]="60",["note"]="",["role"]="Hunter"},
	[16940]={["name"]="Hunter T2 Gloves",["dkp"]="60",["note"]="",["role"]="Hunter"},
	[16937]={["name"]="Hunter T2 Shoulders",["dkp"]="70",["note"]="",["role"]="Hunter"},
	[16942]={["name"]="Hunter T2 Chest",["dkp"]="70",["note"]="",["role"]="Hunter"},
	[16904]={["name"]="Druid T2 Bracers",["dkp"]="60",["note"]="",["role"]="Heal-Druid > Druid"},
	[16903]={["name"]="Druid T2 Belt",["dkp"]="60",["note"]="",["role"]="Heal-Druid > Druid"},
	[16898]={["name"]="Druid T2 Boots",["dkp"]="60",["note"]="",["role"]="Heal-Druid > Druid"},
	[16899]={["name"]="Druid T2 Gloves",["dkp"]="60",["note"]="",["role"]="Heal-Druid > Druid"},
	[16902]={["name"]="Druid T2 Shoulders",["dkp"]="5",["note"]="",["role"]="Druid"},
	[16897]={["name"]="Druid T2 Chest",["dkp"]="70",["note"]="",["role"]="Heal-Druid > Druid"},
	[16943]={["name"]="Shaman T2 Bracers",["dkp"]="60",["note"]="",["role"]="Resto-Shaman > Shaman"},
	[16944]={["name"]="Shaman T2 Belt",["dkp"]="60",["note"]="",["role"]="Resto-Shaman > Shaman"},
	[16949]={["name"]="Shaman T2 Boots",["dkp"]="60",["note"]="",["role"]="Resto-Shaman > Shaman"},
	[16948]={["name"]="Shaman T2 Gloves",["dkp"]="60",["note"]="",["role"]="Resto-Shaman > Shaman"},
	[16945]={["name"]="Shaman T2 Shoulders",["dkp"]="70",["note"]="",["role"]="Resto-Shaman > Shaman"},
	[16950]={["name"]="Shaman T2 Chest",["dkp"]="70",["note"]="",["role"]="Resto-Shaman > Shaman"},
	[19436]={["name"]="Cloak of Draconic Might",["dkp"]="65",["note"]="",["role"]="Warrior > Enhance-Shaman"},
	[19439]={["name"]="Interlaced Shadow Jerkin",["dkp"]="5",["note"]="",["role"]="Feral > Resistance for Leather wearers"},
	[19437]={["name"]="Boots of Pure Thought",["dkp"]="60",["note"]="",["role"]="Heal-Priest = Heal-Druid > Resto-Shaman"},
	[19438]={["name"]="Ringo's Blizzard Boots",["dkp"]="60",["note"]="",["role"]="Mage"},
	[19434]={["name"]="Band of Dark Dominion",["dkp"]="60",["note"]="",["role"]="Shadow-Priest = Warlock"},
	[19435]={["name"]="Essence Gatherer",["dkp"]="35",["note"]="",["role"]="Heal-Priest"},
	[19362]={["name"]="Doom's Edge",["dkp"]="120",["note"]="",["role"]="Orc-Fury-Warrior > Warrior"},
	[19354]={["name"]="Draconic Avenger",["dkp"]="5",["note"]="",["role"]="Warrior = Enhance-Shaman"},
	[19358]={["name"]="Draconic Maul",["dkp"]="5",["note"]="",["role"]="Warrior = Enhance-Shaman"},
	[19370]={["name"]="Mantle of the Blackwing Cabal",["dkp"]="70",["note"]="",["role"]="Mage = Warlock = Shadow-Priest > Heal-Priest"},
	[19369]={["name"]="Gloves of Rapid Evolution",["dkp"]="5",["note"]="",["role"]="Heal-Priest"},
	[19335]={["name"]="Spineshatter",["dkp"]="120",["note"]="",["role"]="Tank-Warrior > Warrior"},
	[19334]={["name"]="The Untamed Blade",["dkp"]="65",["note"]="",["role"]="Warrior"},
	[19336]={["name"]="Arcane Infused Gem",["dkp"]="5",["note"]="",["role"]="Hunter"},
	[19337]={["name"]="The Black Book",["dkp"]="5",["note"]="",["role"]="Warlock"},
	[19372]={["name"]="Helm of Endless Rage",["dkp"]="30",["note"]="",["role"]="Warrior"},
	[19371]={["name"]="Pendant of the Fallen Dragon",["dkp"]="70",["note"]="",["role"]="Resto-Shaman"},
	[19348]={["name"]="Red Dragonscale Protector",["dkp"]="90",["note"]="",["role"]="Resto-Shaman"},
	[19346]={["name"]="Dragonfang Blade",["dkp"]="120",["note"]="",["role"]="Warrior = Rogue"},
	[19339]={["name"]="Mind Quickening Gem",["dkp"]="65",["note"]="",["role"]="Mage"},
	[19340]={["name"]="Rune of Metamorphosis",["dkp"]="5",["note"]="",["role"]="Druid"},
	[19373]={["name"]="Black Brood Pauldrons",["dkp"]="70",["note"]="",["role"]="Enhance-Shaman > Hunter"},
	[19374]={["name"]="Bracers of Arcane Accuracy",["dkp"]="60",["note"]="",["role"]="Mage = Warlock"},
	[19350]={["name"]="Heartstriker",["dkp"]="90",["note"]="",["role"]="???"},
	[19351]={["name"]="Maladath",["dkp"]="120",["note"]="",["role"]="Rogue = Tank-Warrior = Non-Orc-Fury-Warrior > Fury-Warrior"},
	[19341]={["name"]="Lifegiving Gem",["dkp"]="5",["note"]="",["role"]="Warrior"},
	[19342]={["name"]="Venomous Totem",["dkp"]="5",["note"]="",["role"]="Rogue"},
	[19394]={["name"]="Drake Talon Pauldrons",["dkp"]="70",["note"]="",["role"]="Tank-Warrior > Fury-Warrior"},
	[19398]={["name"]="Cloak of Firemaw",["dkp"]="65",["note"]="",["role"]="Rogue > Fury-Warrior"},
	[19399]={["name"]="Black Ash Robe",["dkp"]="5",["note"]="",["role"]="Any Caster FR Gear"},
	[19400]={["name"]="Firemaws Clutch",["dkp"]="60",["note"]="",["role"]="Shadow-Priest > Warlock = Mage = Ele-Shaman"},
	[19396]={["name"]="Taut Dragonhide Belt",["dkp"]="60",["note"]="",["role"]="Feral-Druid > Rogue"},
	[19401]={["name"]="Primalist's Linked Legguards",["dkp"]="70",["note"]="",["role"]="Ele-Shaman"},
	[19402]={["name"]="Legguards of the Fallen Crusader",["dkp"]="70",["note"]="",["role"]="Fury-Warrior"},
	[19365]={["name"]="Claw of the Black Drake",["dkp"]="120",["note"]="",["role"]="Warrior > Rogue"},
	[19353]={["name"]="Drake Talon Cleaver",["dkp"]="120",["note"]="",["role"]="Enhance-Shaman > Warrior"},
	[19355]={["name"]="Shadow Wing Focus Staff",["dkp"]="120",["note"]="",["role"]="Mage = Warlock"},
	[19397]={["name"]="Ring of Blackrock",["dkp"]="60",["note"]="",["role"]="Warlock = Shaman"},
	[19395]={["name"]="Rejuvenating Gem",["dkp"]="65",["note"]="",["role"]="Heal-Priest = Resto-Shaman = Heal-Druid"},
	[19344]={["name"]="Natural Alignment Crystal",["dkp"]="65",["note"]="",["role"]="Ele-Shaman > Shaman"},
	[19407]={["name"]="Ebony Flame Gloves",["dkp"]="60",["note"]="",["role"]="Shadow-Priest = Warlock"},
	[19405]={["name"]="Malfurion's Blessed Bulwark",["dkp"]="70",["note"]="",["role"]="Feral-Druid > Fury-Warrior"},
	[19368]={["name"]="Dragonbreath Hand Cannon",["dkp"]="90",["note"]="",["role"]="Tank-Warrior > Fury-Warrior"},
	[19403]={["name"]="Band of Forced Concentration",["dkp"]="60",["note"]="",["role"]="Warlock = Mage = Ele-Shaman = Shadow-Priest"},
	[19345]={["name"]="Aegis of Preservation",["dkp"]="5",["note"]="",["role"]="Priest"},
	[19406]={["name"]="Drake Fang Talisman",["dkp"]="120",["note"]="",["role"]="Warrior = Rogue = Hunter"},
	[19433]={["name"]="Emberweave Leggings",["dkp"]="5",["note"]="",["role"]="FR Gear for Hunter/Shaman"},
	[19367]={["name"]="Dragon's Touch",["dkp"]="5",["note"]="",["role"]="Mage = Warlock = Priest"},
	[19357]={["name"]="Herald of Woe",["dkp"]="120",["note"]="",["role"]="Enhance-Shaman"},
	[19432]={["name"]="Circle of Applied Force",["dkp"]="60",["note"]="",["role"]="Fury-Warrior = Enhance-Shaman"},
	[19431]={["name"]="Styleen's Impending Scarab",["dkp"]="65",["note"]="",["role"]="Tank-Warrior > Feral-Druid"},
	[19389]={["name"]="Taut Dragonhide Shoulderpads",["dkp"]="70",["note"]="",["role"]="Feral-Druid > Rogue"},
	[19386]={["name"]="Elementium Threaded Cloak",["dkp"]="65",["note"]="",["role"]="Feral-Druid > Tank-Warrior > Enhance-Shaman Shaman"},
	[19390]={["name"]="Taut Dragonhide Gloves",["dkp"]="5",["note"]="",["role"]="Leather Wearers"},
	[19388]={["name"]="Angelista's Grasp",["dkp"]="60",["note"]="",["role"]="Mage = Warlock = Shadow-Priest"},
	[19393]={["name"]="Primalist's Linked Waistguard",["dkp"]="5",["note"]="",["role"]="Shaman"},
	[19392]={["name"]="Girdle of the Fallen Crusader",["dkp"]="5",["note"]="",["role"]="Warrior"},
	[19385]={["name"]="Empowered Leggings",["dkp"]="70",["note"]="",["role"]="Heal-Priest = Heal-Druid > Resto-Shaman"},
	[19391]={["name"]="Shimmering Geta",["dkp"]="60",["note"]="",["role"]="Resto-Shaman > Heal-Priest > Heal-Druid"},
	[19387]={["name"]="Chromatic Boots",["dkp"]="60",["note"]="",["role"]="Warrior"},
	[19361]={["name"]="Ashjre'thul Crossbow",["dkp"]="120",["note"]="",["role"]="Hunter"},
	[19349]={["name"]="Elementium Reinforced Bulwark",["dkp"]="90",["note"]="",["role"]="Tank-Warrior"},
	[19347]={["name"]="Claw of Chromaggus",["dkp"]="120",["note"]="",["role"]="Resto-Shaman > Warlock = Mage > Heal-Priest"},
	[19352]={["name"]="Chromatically Tempered Sword",["dkp"]="120",["note"]="",["role"]="Non-Orc-Fury-Warrior = Rogue"},
	[19360]={["name"]="Lok'amir",["dkp"]="120",["note"]="",["role"]="Shadow-Priest = Ele > Resto Sham = Heal-Druid > Heal-Priest"},
	[19363]={["name"]="Crul'shorukh",["dkp"]="120",["note"]="",["role"]="Orc-Fury-Warrior > Warrior"},
	[19364]={["name"]="Ashkandi",["dkp"]="65",["note"]="",["role"]="Warrior"},
	[19356]={["name"]="Staff of Shadow Flame",["dkp"]="120",["note"]="",["role"]="Mage = Warlock"},
	[19375]={["name"]="Mish'undare",["dkp"]="70",["note"]="",["role"]="Mage = Warlock = Shadow-Priest > Heal-Druid = Heal-Priest"},
	[19377]={["name"]="Prestor's Talisman of Connivery",["dkp"]="70",["note"]="",["role"]="Rogue = Hunter"},
	[19378]={["name"]="Cloak of the Brood Lord",["dkp"]="65",["note"]="",["role"]="Mage = Warlock = Shadow-Priest = Ele-Shaman > Heal-Priest"},
	[19380]={["name"]="Therazane's Link",["dkp"]="60",["note"]="",["role"]="Enhance-Shaman"},
	[19381]={["name"]="Boots of the Shadow Flame",["dkp"]="60",["note"]="",["role"]="Rogue = Enhance-Shaman > Fury-Warrior"},
	[19376]={["name"]="Archimtiros Ring of Reckoning",["dkp"]="5",["note"]="",["role"]="Rogue = Hunter = Fury-Warrior = Feral-Druid"},
	[19382]={["name"]="Pure Elementium Band",["dkp"]="60",["note"]="",["role"]="Heal-Priest = Resto-Shaman = Heal-Druid"},
	[19379]={["name"]="Neltharion's Tear",["dkp"]="65",["note"]="",["role"]="Mage = Warlock = Ele-Shaman = Shadow-Priest"},
	[19003]={["name"]="Head of Nefarian",["dkp"]="60",["note"]="",["role"]="Enhance = Warrior = Rogue = Feral-Druid = Shadow-Priest = Hunter"},
}
